// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: MDCoreSync.proto

package mdCoreSync

import (
	"reflect"
	"sync"
	"unsafe"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LSResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ControlHeader     []byte                 `protobuf:"bytes,1,opt,name=controlHeader" json:"controlHeader,omitempty"`
	Operations        []*Operation           `protobuf:"bytes,2,rep,name=operations" json:"operations,omitempty"`
	TransactionParams *TransactionParams     `protobuf:"bytes,3,opt,name=transactionParams" json:"transactionParams,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LSResponse) Reset() {
	*x = LSResponse{}
	mi := &file_MDCoreSync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LSResponse) ProtoMessage() {}

func (x *LSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LSResponse.ProtoReflect.Descriptor instead.
func (*LSResponse) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{0}
}

func (x *LSResponse) GetControlHeader() []byte {
	if x != nil {
		return x.ControlHeader
	}
	return nil
}

func (x *LSResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *LSResponse) GetTransactionParams() *TransactionParams {
	if x != nil {
		return x.TransactionParams
	}
	return nil
}

type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Operation_Subscribe
	//	*Operation_Resnapshot
	//	*Operation_Delta
	//	*Operation_Noop
	//	*Operation_Failure
	Operation     isOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_MDCoreSync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetOperation() isOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Operation) GetSubscribe() *OnIrisSubscribe {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Operation) GetResnapshot() *OnResnapshot {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Resnapshot); ok {
			return x.Resnapshot
		}
	}
	return nil
}

func (x *Operation) GetDelta() *OnMailboxDelta {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *Operation) GetNoop() *Noop {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Noop); ok {
			return x.Noop
		}
	}
	return nil
}

func (x *Operation) GetFailure() *HandleSyncFailure {
	if x != nil {
		if x, ok := x.Operation.(*Operation_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isOperation_Operation interface {
	isOperation_Operation()
}

type Operation_Subscribe struct {
	Subscribe *OnIrisSubscribe `protobuf:"bytes,1,opt,name=subscribe,oneof"`
}

type Operation_Resnapshot struct {
	Resnapshot *OnResnapshot `protobuf:"bytes,2,opt,name=resnapshot,oneof"`
}

type Operation_Delta struct {
	Delta *OnMailboxDelta `protobuf:"bytes,3,opt,name=delta,oneof"`
}

type Operation_Noop struct {
	Noop *Noop `protobuf:"bytes,4,opt,name=noop,oneof"`
}

type Operation_Failure struct {
	Failure *HandleSyncFailure `protobuf:"bytes,5,opt,name=failure,oneof"`
}

func (*Operation_Subscribe) isOperation_Operation() {}

func (*Operation_Resnapshot) isOperation_Operation() {}

func (*Operation_Delta) isOperation_Operation() {}

func (*Operation_Noop) isOperation_Operation() {}

func (*Operation_Failure) isOperation_Operation() {}

type OnIrisSubscribe struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupID         *int32                 `protobuf:"varint,1,opt,name=groupID" json:"groupID,omitempty"`
	SubscribedSeqID *int64                 `protobuf:"varint,2,opt,name=subscribedSeqID" json:"subscribedSeqID,omitempty"`
	LatestSeqID     *int64                 `protobuf:"varint,3,opt,name=latestSeqID" json:"latestSeqID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnIrisSubscribe) Reset() {
	*x = OnIrisSubscribe{}
	mi := &file_MDCoreSync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnIrisSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnIrisSubscribe) ProtoMessage() {}

func (x *OnIrisSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnIrisSubscribe.ProtoReflect.Descriptor instead.
func (*OnIrisSubscribe) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{2}
}

func (x *OnIrisSubscribe) GetGroupID() int32 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *OnIrisSubscribe) GetSubscribedSeqID() int64 {
	if x != nil && x.SubscribedSeqID != nil {
		return *x.SubscribedSeqID
	}
	return 0
}

func (x *OnIrisSubscribe) GetLatestSeqID() int64 {
	if x != nil && x.LatestSeqID != nil {
		return *x.LatestSeqID
	}
	return 0
}

type OnResnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupID         *int32                 `protobuf:"varint,1,opt,name=groupID" json:"groupID,omitempty"`
	ErrorMessage    *string                `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
	ErrorType       *int32                 `protobuf:"varint,3,opt,name=errorType" json:"errorType,omitempty"`
	SnapshotPayload []byte                 `protobuf:"bytes,4,opt,name=snapshotPayload" json:"snapshotPayload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnResnapshot) Reset() {
	*x = OnResnapshot{}
	mi := &file_MDCoreSync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnResnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnResnapshot) ProtoMessage() {}

func (x *OnResnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnResnapshot.ProtoReflect.Descriptor instead.
func (*OnResnapshot) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{3}
}

func (x *OnResnapshot) GetGroupID() int32 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *OnResnapshot) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *OnResnapshot) GetErrorType() int32 {
	if x != nil && x.ErrorType != nil {
		return *x.ErrorType
	}
	return 0
}

func (x *OnResnapshot) GetSnapshotPayload() []byte {
	if x != nil {
		return x.SnapshotPayload
	}
	return nil
}

type OnMailboxDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       *int32                 `protobuf:"varint,1,opt,name=groupID" json:"groupID,omitempty"`
	Delta         *string                `protobuf:"bytes,2,opt,name=delta" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnMailboxDelta) Reset() {
	*x = OnMailboxDelta{}
	mi := &file_MDCoreSync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnMailboxDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnMailboxDelta) ProtoMessage() {}

func (x *OnMailboxDelta) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnMailboxDelta.ProtoReflect.Descriptor instead.
func (*OnMailboxDelta) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{4}
}

func (x *OnMailboxDelta) GetGroupID() int32 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *OnMailboxDelta) GetDelta() string {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return ""
}

type Noop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Noop) Reset() {
	*x = Noop{}
	mi := &file_MDCoreSync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Noop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noop) ProtoMessage() {}

func (x *Noop) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noop.ProtoReflect.Descriptor instead.
func (*Noop) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{5}
}

type HandleSyncFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       *int32                 `protobuf:"varint,1,req,name=groupID" json:"groupID,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,2,req,name=errorMessage" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleSyncFailure) Reset() {
	*x = HandleSyncFailure{}
	mi := &file_MDCoreSync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleSyncFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleSyncFailure) ProtoMessage() {}

func (x *HandleSyncFailure) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleSyncFailure.ProtoReflect.Descriptor instead.
func (*HandleSyncFailure) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{6}
}

func (x *HandleSyncFailure) GetGroupID() int32 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *HandleSyncFailure) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

type TransactionParams struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UseTransactionLogic *bool                  `protobuf:"varint,1,opt,name=useTransactionLogic" json:"useTransactionLogic,omitempty"`
	GroupID             *int32                 `protobuf:"varint,2,opt,name=groupID" json:"groupID,omitempty"`
	SyncEpochID         *int64                 `protobuf:"varint,3,opt,name=syncEpochID" json:"syncEpochID,omitempty"`
	PreviousCursor      *string                `protobuf:"bytes,4,opt,name=previousCursor" json:"previousCursor,omitempty"`
	NextCursor          *string                `protobuf:"bytes,5,opt,name=nextCursor" json:"nextCursor,omitempty"`
	SyncStatus          *int32                 `protobuf:"varint,6,opt,name=syncStatus" json:"syncStatus,omitempty"`
	SyncChannel         *int32                 `protobuf:"varint,7,opt,name=syncChannel" json:"syncChannel,omitempty"`
	UserID              *int64                 `protobuf:"varint,8,opt,name=userID" json:"userID,omitempty"`
	SkipMismatchLog     *bool                  `protobuf:"varint,9,opt,name=skipMismatchLog" json:"skipMismatchLog,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransactionParams) Reset() {
	*x = TransactionParams{}
	mi := &file_MDCoreSync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionParams) ProtoMessage() {}

func (x *TransactionParams) ProtoReflect() protoreflect.Message {
	mi := &file_MDCoreSync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionParams.ProtoReflect.Descriptor instead.
func (*TransactionParams) Descriptor() ([]byte, []int) {
	return file_MDCoreSync_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionParams) GetUseTransactionLogic() bool {
	if x != nil && x.UseTransactionLogic != nil {
		return *x.UseTransactionLogic
	}
	return false
}

func (x *TransactionParams) GetGroupID() int32 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *TransactionParams) GetSyncEpochID() int64 {
	if x != nil && x.SyncEpochID != nil {
		return *x.SyncEpochID
	}
	return 0
}

func (x *TransactionParams) GetPreviousCursor() string {
	if x != nil && x.PreviousCursor != nil {
		return *x.PreviousCursor
	}
	return ""
}

func (x *TransactionParams) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

func (x *TransactionParams) GetSyncStatus() int32 {
	if x != nil && x.SyncStatus != nil {
		return *x.SyncStatus
	}
	return 0
}

func (x *TransactionParams) GetSyncChannel() int32 {
	if x != nil && x.SyncChannel != nil {
		return *x.SyncChannel
	}
	return 0
}

func (x *TransactionParams) GetUserID() int64 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *TransactionParams) GetSkipMismatchLog() bool {
	if x != nil && x.SkipMismatchLog != nil {
		return *x.SkipMismatchLog
	}
	return false
}

var File_MDCoreSync_proto protoreflect.FileDescriptor

const file_MDCoreSync_proto_rawDesc = "" +
	"\n" +
	"\x10MDCoreSync.proto\x12\n" +
	"mdCoreSync\"\xb6\x01\n" +
	"\n" +
	"LSResponse\x12$\n" +
	"\rcontrolHeader\x18\x01 \x01(\fR\rcontrolHeader\x125\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x15.mdCoreSync.OperationR\n" +
	"operations\x12K\n" +
	"\x11transactionParams\x18\x03 \x01(\v2\x1d.mdCoreSync.TransactionParamsR\x11transactionParams\"\xa8\x02\n" +
	"\tOperation\x12;\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1b.mdCoreSync.OnIrisSubscribeH\x00R\tsubscribe\x12:\n" +
	"\n" +
	"resnapshot\x18\x02 \x01(\v2\x18.mdCoreSync.OnResnapshotH\x00R\n" +
	"resnapshot\x122\n" +
	"\x05delta\x18\x03 \x01(\v2\x1a.mdCoreSync.OnMailboxDeltaH\x00R\x05delta\x12&\n" +
	"\x04noop\x18\x04 \x01(\v2\x10.mdCoreSync.NoopH\x00R\x04noop\x129\n" +
	"\afailure\x18\x05 \x01(\v2\x1d.mdCoreSync.HandleSyncFailureH\x00R\afailureB\v\n" +
	"\toperation\"w\n" +
	"\x0fOnIrisSubscribe\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\x05R\agroupID\x12(\n" +
	"\x0fsubscribedSeqID\x18\x02 \x01(\x03R\x0fsubscribedSeqID\x12 \n" +
	"\vlatestSeqID\x18\x03 \x01(\x03R\vlatestSeqID\"\x94\x01\n" +
	"\fOnResnapshot\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\x05R\agroupID\x12\"\n" +
	"\ferrorMessage\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\terrorType\x18\x03 \x01(\x05R\terrorType\x12(\n" +
	"\x0fsnapshotPayload\x18\x04 \x01(\fR\x0fsnapshotPayload\"@\n" +
	"\x0eOnMailboxDelta\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\x05R\agroupID\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\"\x06\n" +
	"\x04Noop\"Q\n" +
	"\x11HandleSyncFailure\x12\x18\n" +
	"\agroupID\x18\x01 \x02(\x05R\agroupID\x12\"\n" +
	"\ferrorMessage\x18\x02 \x02(\tR\ferrorMessage\"\xcd\x02\n" +
	"\x11TransactionParams\x120\n" +
	"\x13useTransactionLogic\x18\x01 \x01(\bR\x13useTransactionLogic\x12\x18\n" +
	"\agroupID\x18\x02 \x01(\x05R\agroupID\x12 \n" +
	"\vsyncEpochID\x18\x03 \x01(\x03R\vsyncEpochID\x12&\n" +
	"\x0epreviousCursor\x18\x04 \x01(\tR\x0epreviousCursor\x12\x1e\n" +
	"\n" +
	"nextCursor\x18\x05 \x01(\tR\n" +
	"nextCursor\x12\x1e\n" +
	"\n" +
	"syncStatus\x18\x06 \x01(\x05R\n" +
	"syncStatus\x12 \n" +
	"\vsyncChannel\x18\a \x01(\x05R\vsyncChannel\x12\x16\n" +
	"\x06userID\x18\b \x01(\x03R\x06userID\x12(\n" +
	"\x0fskipMismatchLog\x18\t \x01(\bR\x0fskipMismatchLogB0Z.go.mau.fi/mautrix-meta/pkg/messagix/mdCoreSync"

var (
	file_MDCoreSync_proto_rawDescOnce sync.Once
	file_MDCoreSync_proto_rawDescData []byte
)

func file_MDCoreSync_proto_rawDescGZIP() []byte {
	file_MDCoreSync_proto_rawDescOnce.Do(func() {
		file_MDCoreSync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_MDCoreSync_proto_rawDesc), len(file_MDCoreSync_proto_rawDesc)))
	})
	return file_MDCoreSync_proto_rawDescData
}

var file_MDCoreSync_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_MDCoreSync_proto_goTypes = []any{
	(*LSResponse)(nil),        // 0: mdCoreSync.LSResponse
	(*Operation)(nil),         // 1: mdCoreSync.Operation
	(*OnIrisSubscribe)(nil),   // 2: mdCoreSync.OnIrisSubscribe
	(*OnResnapshot)(nil),      // 3: mdCoreSync.OnResnapshot
	(*OnMailboxDelta)(nil),    // 4: mdCoreSync.OnMailboxDelta
	(*Noop)(nil),              // 5: mdCoreSync.Noop
	(*HandleSyncFailure)(nil), // 6: mdCoreSync.HandleSyncFailure
	(*TransactionParams)(nil), // 7: mdCoreSync.TransactionParams
}
var file_MDCoreSync_proto_depIdxs = []int32{
	1, // 0: mdCoreSync.LSResponse.operations:type_name -> mdCoreSync.Operation
	7, // 1: mdCoreSync.LSResponse.transactionParams:type_name -> mdCoreSync.TransactionParams
	2, // 2: mdCoreSync.Operation.subscribe:type_name -> mdCoreSync.OnIrisSubscribe
	3, // 3: mdCoreSync.Operation.resnapshot:type_name -> mdCoreSync.OnResnapshot
	4, // 4: mdCoreSync.Operation.delta:type_name -> mdCoreSync.OnMailboxDelta
	5, // 5: mdCoreSync.Operation.noop:type_name -> mdCoreSync.Noop
	6, // 6: mdCoreSync.Operation.failure:type_name -> mdCoreSync.HandleSyncFailure
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_MDCoreSync_proto_init() }
func file_MDCoreSync_proto_init() {
	if File_MDCoreSync_proto != nil {
		return
	}
	file_MDCoreSync_proto_msgTypes[1].OneofWrappers = []any{
		(*Operation_Subscribe)(nil),
		(*Operation_Resnapshot)(nil),
		(*Operation_Delta)(nil),
		(*Operation_Noop)(nil),
		(*Operation_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_MDCoreSync_proto_rawDesc), len(file_MDCoreSync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MDCoreSync_proto_goTypes,
		DependencyIndexes: file_MDCoreSync_proto_depIdxs,
		MessageInfos:      file_MDCoreSync_proto_msgTypes,
	}.Build()
	File_MDCoreSync_proto = out.File
	file_MDCoreSync_proto_goTypes = nil
	file_MDCoreSync_proto_depIdxs = nil
}
