package messagix

type ConnectionCode uint8
const (
	CONNECTION_ACCEPTED ConnectionCode = iota
	CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION
	CONNECTION_REFUSED_IDENTIFIER_REJECTED
	CONNECTION_REFUSED_SERVER_UNAVAILABLE
	CONNECTION_REFUSED_BAD_USERNAME_OR_PASSWORD
	CONNECTION_REFUSED_UNAUTHORIZED
)

var connectionCodesNames = map[ConnectionCode]string{
	CONNECTION_ACCEPTED:                                "CONNECTION_ACCEPTED",
	CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION:   "CONNECTION_REFUSED_UNACCEPTABLE_PROTOCOL_VERSION",
	CONNECTION_REFUSED_IDENTIFIER_REJECTED:             "CONNECTION_REFUSED_IDENTIFIER_REJECTED",
	CONNECTION_REFUSED_SERVER_UNAVAILABLE:              "CONNECTION_REFUSED_SERVER_UNAVAILABLE",
	CONNECTION_REFUSED_BAD_USERNAME_OR_PASSWORD:        "CONNECTION_REFUSED_BAD_USERNAME_OR_PASSWORD",
	CONNECTION_REFUSED_UNAUTHORIZED:                    "CONNECTION_REFUSED_UNAUTHORIZED",
}

func (c ConnectionCode) ToString() string {
	if name, ok := connectionCodesNames[c]; ok {
		return name
	}
	return "UNKNOWN_CONNECTION_CODE"
}
func (c ConnectionCode) IsEnum() {}