package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync/atomic"
	"time"
)

// Persisted GraphQL doc_ids rotate. Nothing in this file hard-codes one: the
// registry is generated by `bsprobe har` from a real capture, and roles.json
// maps a semantic role ("list_threads") onto whatever friendly_name that
// capture revealed. When Meta rotates, you re-capture and re-run har — you do
// not edit Go code.

type Registry struct {
	Operations []*Operation      `json:"operations"`
	Roles      map[string]string `json:"-"`
	dir        string
}

// KnownRoles are the operations a minimum viable connector needs, in the order
// the spec's Phase 1 and Phase 2 require them.
var KnownRoles = []string{
	"list_businesses",
	"list_assets",
	"list_mailboxes",
	"list_threads",
	"get_thread",
	"send_text",
	"mark_read",
}

func LoadRegistry(dir string) (*Registry, error) {
	r := &Registry{dir: dir, Roles: map[string]string{}}

	raw, err := os.ReadFile(filepath.Join(dir, "operations.json"))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("no operations.json in %s\n\n"+
				"Record a DevTools HAR of the inbox, then run:\n"+
				"  bsprobe har --out %s <capture.har>", dir, dir)
		}
		return nil, err
	}
	if err := json.Unmarshal(raw, r); err != nil {
		return nil, fmt.Errorf("parse operations.json: %w", err)
	}

	rolesRaw, err := os.ReadFile(filepath.Join(dir, "roles.json"))
	if err == nil {
		if err := json.Unmarshal(rolesRaw, &r.Roles); err != nil {
			return nil, fmt.Errorf("parse roles.json: %w", err)
		}
	} else if !os.IsNotExist(err) {
		return nil, err
	}
	return r, nil
}

func (r *Registry) Get(friendlyName string) (*Operation, bool) {
	for _, op := range r.Operations {
		if op.FriendlyName == friendlyName {
			return op, true
		}
	}
	return nil, false
}

func (r *Registry) ForRole(role string) (*Operation, error) {
	name, ok := r.Roles[role]
	if !ok || name == "" {
		return nil, fmt.Errorf("role %q is not mapped\n\n"+
			"Open %s and pick the friendly_name that matches, then add it to %s:\n"+
			"  { %q: \"<FriendlyNameFromCapture>\" }\n\n"+
			"Captured operations are listed in operations.json.",
			role,
			filepath.Join(r.dir, "operations.json"),
			filepath.Join(r.dir, "roles.json"),
			role)
	}
	op, ok := r.Get(name)
	if !ok {
		return nil, fmt.Errorf("role %q maps to %q, which is not in operations.json (re-capture?)", role, name)
	}
	if op.DocID == "" {
		return nil, fmt.Errorf("operation %q has no doc_id in the capture", name)
	}
	return op, nil
}

// WriteRolesTemplate drops a roles.json skeleton so the mapping step is
// obvious rather than folklore.
func (r *Registry) WriteRolesTemplate() error {
	path := filepath.Join(r.dir, "roles.json")
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	m := map[string]string{}
	for _, role := range KnownRoles {
		m[role] = ""
	}
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

var reqCounter atomic.Int64

// Call issues one persisted GraphQL request using the session and bootstrap
// tokens. Field names here (av, __user, fb_dtsg, doc_id, ...) are the standard
// Meta web-client form fields; if a capture shows Business Suite using
// different ones, this is the single place to change.
func (s *Session) Call(b *Bootstrap, op *Operation, vars map[string]any) (int, string, error) {
	varsJSON, err := json.Marshal(vars)
	if err != nil {
		return 0, "", err
	}

	form := url.Values{}
	form.Set("av", b.CurrentUserID)
	form.Set("__user", b.CurrentUserID)
	form.Set("__a", "1")
	form.Set("__req", strconv.FormatInt(reqCounter.Add(1), 36))
	form.Set("fb_dtsg", b.FBDTSG)
	form.Set("jazoest", b.Jazoest)
	form.Set("lsd", b.LSD)
	form.Set("fb_api_caller_class", "RelayModern")
	form.Set("fb_api_req_friendly_name", op.FriendlyName)
	form.Set("variables", string(varsJSON))
	form.Set("server_timestamps", "true")
	form.Set("doc_id", op.DocID)
	if b.Rev != "" {
		form.Set("__rev", b.Rev)
	}

	endpoint := op.Endpoint
	if endpoint == "" {
		endpoint = businessHost + "/api/graphql/"
	}

	req, err := http.NewRequest(http.MethodPost, endpoint, strings.NewReader(form.Encode()))
	if err != nil {
		return 0, "", err
	}
	req.Header.Set("User-Agent", s.UserAgent)
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "*/*")
	req.Header.Set("Origin", businessHost)
	req.Header.Set("Referer", businessHost+"/latest/inbox/all")
	req.Header.Set("X-FB-Friendly-Name", op.FriendlyName)
	req.Header.Set("X-FB-LSD", b.LSD)
	req.Header.Set("Sec-Fetch-Dest", "empty")
	req.Header.Set("Sec-Fetch-Mode", "cors")
	req.Header.Set("Sec-Fetch-Site", "same-origin")

	client := *s.client
	client.Timeout = 45 * time.Second
	resp, err := client.Do(req)
	if err != nil {
		return 0, "", err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(io.LimitReader(resp.Body, 32<<20))
	if err != nil {
		return resp.StatusCode, "", err
	}
	// Meta prefixes JSON responses with an anti-JSON-hijacking guard.
	return resp.StatusCode, strings.TrimPrefix(string(body), "for (;;);"), nil
}

// runRole is the shared body of list-assets / list-threads / send-test: they
// differ only in which role they resolve and which variables they pass.
func runRole(role string, args []string, buildVars func(*flag.FlagSet) map[string]any, extra func(*flag.FlagSet)) error {
	fs := flag.NewFlagSet(role, flag.ExitOnError)
	sessionPath := fs.String("session", defaultSessionFile, "session file")
	fixtures := fs.String("fixtures", "fixtures", "fixtures directory holding operations.json and roles.json")
	shape := fs.Bool("shape", true, "print the response shape instead of raw values")
	saveShape := fs.String("save-shape", "", "write the response shape to this file")
	if extra != nil {
		extra(fs)
	}
	if err := fs.Parse(args); err != nil {
		return err
	}

	reg, err := LoadRegistry(*fixtures)
	if err != nil {
		return err
	}
	if err := reg.WriteRolesTemplate(); err != nil {
		return err
	}
	op, err := reg.ForRole(role)
	if err != nil {
		return err
	}

	s, err := LoadSession(*sessionPath)
	if err != nil {
		return err
	}
	_, html, err := s.Get(businessHost + "/latest/inbox/all")
	if err != nil {
		return fmt.Errorf("fetch bootstrap: %w", err)
	}
	b := ParseBootstrap(html)
	if b.FBDTSG == "" {
		return fmt.Errorf("no fb_dtsg in bootstrap - run 'bsprobe validate-session' first")
	}

	vars := map[string]any{}
	if buildVars != nil {
		vars = buildVars(fs)
	}

	fmt.Printf("%s -> %s (doc_id=%s)\n", role, op.FriendlyName, op.DocID)
	status, body, err := s.Call(b, op, vars)
	if err != nil {
		return err
	}
	fmt.Printf("HTTP %d, %d bytes\n\n", status, len(body))

	var decoded any
	if err := json.Unmarshal([]byte(body), &decoded); err != nil {
		trimmed := body
		if len(trimmed) > 800 {
			trimmed = trimmed[:800]
		}
		return fmt.Errorf("response was not JSON:\n%s", RedactString(trimmed))
	}

	if m, ok := decoded.(map[string]any); ok {
		if errs, ok := m["errors"]; ok {
			out, _ := json.MarshalIndent(Redact(errs), "", "  ")
			fmt.Printf("GraphQL errors:\n%s\n", out)
		}
	}

	var out []byte
	if *shape {
		out, _ = json.MarshalIndent(Shape(decoded), "", "  ")
	} else {
		out, _ = json.MarshalIndent(Redact(decoded), "", "  ")
	}
	fmt.Println(string(out))

	if *saveShape != "" {
		if err := os.MkdirAll(filepath.Dir(*saveShape), 0o755); err != nil {
			return err
		}
		payload, _ := json.MarshalIndent(map[string]any{
			"role":          role,
			"friendly_name": op.FriendlyName,
			"doc_id":        op.DocID,
			"shape":         Shape(decoded),
		}, "", "  ")
		if err := os.WriteFile(*saveShape, payload, 0o644); err != nil {
			return err
		}
		fmt.Printf("\nshape written to %s\n", *saveShape)
	}
	return nil
}

func cmdListAssets(args []string) error {
	return runRole("list_assets", args, nil, nil)
}

func cmdListThreads(args []string) error {
	var mailbox *string
	var cursor *string
	var count *int
	return runRole("list_threads", args, func(fs *flag.FlagSet) map[string]any {
		v := map[string]any{"count": *count}
		if *mailbox != "" {
			v["mailbox_id"] = *mailbox
		}
		if *cursor != "" {
			v["cursor"] = *cursor
		}
		return v
	}, func(fs *flag.FlagSet) {
		mailbox = fs.String("mailbox", "", "mailbox id (from bsprobe bootstrap)")
		cursor = fs.String("cursor", "", "pagination cursor")
		count = fs.Int("count", 20, "threads to request")
	})
}

func cmdSendTest(args []string) error {
	var thread *string
	var text *string
	return runRole("send_text", args, func(fs *flag.FlagSet) map[string]any {
		return map[string]any{"thread_id": *thread, "text": *text}
	}, func(fs *flag.FlagSet) {
		thread = fs.String("thread", "", "thread id to send to")
		text = fs.String("text", "bsprobe test", "message body")
	})
}

// cmdCall is the escape hatch: invoke any captured operation with arbitrary
// variables, which is how you work out a variable schema without editing code.
func cmdCall(args []string) error {
	fs := flag.NewFlagSet("call", flag.ExitOnError)
	sessionPath := fs.String("session", defaultSessionFile, "session file")
	fixtures := fs.String("fixtures", "fixtures", "fixtures directory")
	opName := fs.String("op", "", "friendly_name from operations.json")
	varsJSON := fs.String("vars", "{}", "variables as a JSON object")
	shape := fs.Bool("shape", true, "print response shape rather than redacted values")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *opName == "" {
		return fmt.Errorf("--op is required (see operations.json)")
	}

	reg, err := LoadRegistry(*fixtures)
	if err != nil {
		return err
	}
	op, ok := reg.Get(*opName)
	if !ok {
		return fmt.Errorf("operation %q not found in operations.json", *opName)
	}

	var vars map[string]any
	if err := json.Unmarshal([]byte(*varsJSON), &vars); err != nil {
		return fmt.Errorf("--vars must be a JSON object: %w", err)
	}

	s, err := LoadSession(*sessionPath)
	if err != nil {
		return err
	}
	_, html, err := s.Get(businessHost + "/latest/inbox/all")
	if err != nil {
		return err
	}
	b := ParseBootstrap(html)

	status, body, err := s.Call(b, op, vars)
	if err != nil {
		return err
	}
	fmt.Printf("HTTP %d, %d bytes\n\n", status, len(body))

	var decoded any
	if err := json.Unmarshal([]byte(body), &decoded); err != nil {
		trimmed := body
		if len(trimmed) > 800 {
			trimmed = trimmed[:800]
		}
		fmt.Println(RedactString(trimmed))
		return nil
	}
	var out []byte
	if *shape {
		out, _ = json.MarshalIndent(Shape(decoded), "", "  ")
	} else {
		out, _ = json.MarshalIndent(Redact(decoded), "", "  ")
	}
	fmt.Println(string(out))
	return nil
}
