package main

type Minification struct {
	Functions map[BloksFunctionID]BloksFunctionID
}

func ReverseMinify(target *BloksBundle, reference *BloksBundle) (*Minification, error) {
	return &Minification{
		Functions: map[BloksFunctionID]BloksFunctionID{
			// These are sorted by how often they appear
			"e25": "bk.action.core.GetArg",
			"dnt": "bk.action.bloks.GetVariable2",
			"e2a": "bk.action.core.If",
			"dkc": "bk.action.array.Make",
			"e2f": "bk.action.core.TakeLast",
			"e24": "bk.action.core.FuncConst",
			"f6m": "<create single-pair map>",
			"e1w": "bk.action.core.Apply",
			"f4i": "bk.action.map.Make",
			"dqa": "bk.action.bloks.WriteLocalState",
			"e2e": "bk.action.core.SetArg",
			"e56": "bk.action.core.Match",
			"fom": "bk.action.tree.Make",
			"f43": "bk.action.logging.LogEvent",
			"dq8": "bk.action.bloks.WriteGlobalConsistencyStore",
			"dqr": "bk.action.bool.Not",
			"dey": "<logging>",
			"dnk": "<get variable>",
			"djj": "bk.action.animated.easing.CreateCubicBezier",
			"dj3": "bk.action.animated.GetCurrentValue",
			"diu": "bk.action.animated.Create",
			"fna": "bk.action.template.Make",
			"dkf": "bk.action.map.Update",
			"fgx": "bk.action.qpl.MarkerPointV2",
			"fhz": "bk.action.ref.Read",
			"dqs": "",
			"djf": "",
			"fnq": "bk.action.textinput.GetText",
			"f4g": "",
			"dn3": "bk.action.bloks.Find",
			"fh0": "",
			"fgq": "",
			"f4k": "",
			"e53": "",
			"e52": "",
			"dj8": "",
			"f76": "",
			"e3z": "",
			"dpz": "bk.action.bloks.RequestFocus",
			"dn0": "",
			"fmu": "",
			"fme": "",
			"flw": "",
			"f6w": "",
			"e57": "",
			"dy8": "",
			"dhv": "",
			"igq": "",
			"fmf": "",
			"fgu": "",
			"f6g": "",
			"dvy": "",
			"drc": "",
			"h9a": "",
			"fxl": "",
			"fi0": "bk.action.ref.Write",
			"f7c": "",
			"f6t": "",
			"eud": "",
			"esn": "",
			"e55": "",
			"dps": "",
			"doa": "",
			"dk8": "",
			"foe": "",
			"fnj": "",
			"euf": "",
			"e59": "",
			"dw9": "",
			"dr3": "",
			"dqo": "",
			"dnh": "",
			"di0": "",
		},
	}, nil
}
