// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package mqttbypass

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"regexp"
	"strings"
	"time"

	thrift "github.com/apache/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO

// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type ErrorCode int64

const (
	ErrorCode_Unknown ErrorCode = 0
	ErrorCode_Timeout ErrorCode = 1
)

var knownErrorCodeValues = []ErrorCode{
	ErrorCode_Unknown,
	ErrorCode_Timeout,
}

func ErrorCodeValues() iter.Seq[ErrorCode] {
	return func(yield func(ErrorCode) bool) {
		for _, v := range knownErrorCodeValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p ErrorCode) String() string {
	switch p {
	case ErrorCode_Unknown:
		return "Unknown"
	case ErrorCode_Timeout:
		return "Timeout"
	}
	return "<UNSET>"
}

func ErrorCodeFromString(s string) (ErrorCode, error) {
	switch s {
	case "Unknown":
		return ErrorCode_Unknown, nil
	case "Timeout":
		return ErrorCode_Timeout, nil
	}
	return ErrorCode(0), fmt.Errorf("not a valid ErrorCode string")
}

func ErrorCodePtr(v ErrorCode) *ErrorCode { return &v }

func (p ErrorCode) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ErrorCode) UnmarshalText(text []byte) error {
	q, err := ErrorCodeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ErrorCode) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = ErrorCode(v)
	return nil
}

func (p *ErrorCode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//   - TraceId
//   - SamplingReasons
type ClientTraceInfo struct {
	TraceId         int64    `thrift:"traceId,1,required" db:"traceId" json:"traceId"`
	SamplingReasons []string `thrift:"samplingReasons,2,required" db:"samplingReasons" json:"samplingReasons"`
}

func NewClientTraceInfo() *ClientTraceInfo {
	return &ClientTraceInfo{}
}

func (p *ClientTraceInfo) GetTraceId() int64 {
	return p.TraceId
}

func (p *ClientTraceInfo) GetSamplingReasons() []string {
	return p.SamplingReasons
}

func (p *ClientTraceInfo) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetTraceId bool = false
	var issetSamplingReasons bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetTraceId = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetSamplingReasons = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetTraceId {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field TraceId is not set"))
	}
	if !issetSamplingReasons {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field SamplingReasons is not set"))
	}
	return nil
}

func (p *ClientTraceInfo) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.TraceId = v
	}
	return nil
}

func (p *ClientTraceInfo) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.SamplingReasons = tSlice
	for i := 0; i < size; i++ {
		var _elem0 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem0 = v
		}
		p.SamplingReasons = append(p.SamplingReasons, _elem0)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *ClientTraceInfo) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ClientTraceInfo"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ClientTraceInfo) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "traceId", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:traceId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.TraceId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.traceId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:traceId: ", p), err)
	}
	return err
}

func (p *ClientTraceInfo) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "samplingReasons", thrift.LIST, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:samplingReasons: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRING, len(p.SamplingReasons)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.SamplingReasons {
		if err := oprot.WriteString(ctx, string(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:samplingReasons: ", p), err)
	}
	return err
}

func (p *ClientTraceInfo) Equals(other *ClientTraceInfo) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.TraceId != other.TraceId {
		return false
	}
	if len(p.SamplingReasons) != len(other.SamplingReasons) {
		return false
	}
	for i, _tgt := range p.SamplingReasons {
		_src1 := other.SamplingReasons[i]
		if _tgt != _src1 {
			return false
		}
	}
	return true
}

func (p *ClientTraceInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ClientTraceInfo(%+v)", *p)
}

func (p *ClientTraceInfo) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.ClientTraceInfo",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ClientTraceInfo)(nil)

func (p *ClientTraceInfo) Validate() error {
	return nil
}

// Attributes:
//   - Payload
//   - MqttTopic
//   - ClientTraceInfo
type PublishRequest struct {
	Payload         []byte           `thrift:"payload,1,required" db:"payload" json:"payload"`
	MqttTopic       string           `thrift:"mqttTopic,2,required" db:"mqttTopic" json:"mqttTopic"`
	ClientTraceInfo *ClientTraceInfo `thrift:"clientTraceInfo,3" db:"clientTraceInfo" json:"clientTraceInfo,omitempty"`
}

func NewPublishRequest() *PublishRequest {
	return &PublishRequest{}
}

func (p *PublishRequest) GetPayload() []byte {
	return p.Payload
}

func (p *PublishRequest) GetMqttTopic() string {
	return p.MqttTopic
}

var PublishRequest_ClientTraceInfo_DEFAULT *ClientTraceInfo

func (p *PublishRequest) GetClientTraceInfo() *ClientTraceInfo {
	if !p.IsSetClientTraceInfo() {
		return PublishRequest_ClientTraceInfo_DEFAULT
	}
	return p.ClientTraceInfo
}

func (p *PublishRequest) IsSetClientTraceInfo() bool {
	return p.ClientTraceInfo != nil
}

func (p *PublishRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetPayload bool = false
	var issetMqttTopic bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetPayload = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetMqttTopic = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetPayload {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Payload is not set"))
	}
	if !issetMqttTopic {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field MqttTopic is not set"))
	}
	return nil
}

func (p *PublishRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Payload = v
	}
	return nil
}

func (p *PublishRequest) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.MqttTopic = v
	}
	return nil
}

func (p *PublishRequest) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	p.ClientTraceInfo = &ClientTraceInfo{}
	if err := p.ClientTraceInfo.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ClientTraceInfo), err)
	}
	return nil
}

func (p *PublishRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "PublishRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *PublishRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "payload", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:payload: ", p), err)
	}
	if err := oprot.WriteBinary(ctx, p.Payload); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.payload (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:payload: ", p), err)
	}
	return err
}

func (p *PublishRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "mqttTopic", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:mqttTopic: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.MqttTopic)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.mqttTopic (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:mqttTopic: ", p), err)
	}
	return err
}

func (p *PublishRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetClientTraceInfo() {
		if err := oprot.WriteFieldBegin(ctx, "clientTraceInfo", thrift.STRUCT, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:clientTraceInfo: ", p), err)
		}
		if err := p.ClientTraceInfo.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ClientTraceInfo), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:clientTraceInfo: ", p), err)
		}
	}
	return err
}

func (p *PublishRequest) Equals(other *PublishRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if bytes.Compare(p.Payload, other.Payload) != 0 {
		return false
	}
	if p.MqttTopic != other.MqttTopic {
		return false
	}
	if !p.ClientTraceInfo.Equals(other.ClientTraceInfo) {
		return false
	}
	return true
}

func (p *PublishRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishRequest(%+v)", *p)
}

func (p *PublishRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.PublishRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*PublishRequest)(nil)

func (p *PublishRequest) Validate() error {
	return nil
}

// Attributes:
//   - Payload
//   - MqttTopic
type PublishResponse struct {
	Payload   []byte `thrift:"payload,1,required" db:"payload" json:"payload"`
	MqttTopic string `thrift:"mqttTopic,2,required" db:"mqttTopic" json:"mqttTopic"`
}

func NewPublishResponse() *PublishResponse {
	return &PublishResponse{}
}

func (p *PublishResponse) GetPayload() []byte {
	return p.Payload
}

func (p *PublishResponse) GetMqttTopic() string {
	return p.MqttTopic
}

func (p *PublishResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetPayload bool = false
	var issetMqttTopic bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetPayload = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetMqttTopic = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetPayload {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Payload is not set"))
	}
	if !issetMqttTopic {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field MqttTopic is not set"))
	}
	return nil
}

func (p *PublishResponse) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Payload = v
	}
	return nil
}

func (p *PublishResponse) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.MqttTopic = v
	}
	return nil
}

func (p *PublishResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "PublishResponse"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *PublishResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "payload", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:payload: ", p), err)
	}
	if err := oprot.WriteBinary(ctx, p.Payload); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.payload (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:payload: ", p), err)
	}
	return err
}

func (p *PublishResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "mqttTopic", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:mqttTopic: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.MqttTopic)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.mqttTopic (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:mqttTopic: ", p), err)
	}
	return err
}

func (p *PublishResponse) Equals(other *PublishResponse) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if bytes.Compare(p.Payload, other.Payload) != 0 {
		return false
	}
	if p.MqttTopic != other.MqttTopic {
		return false
	}
	return true
}

func (p *PublishResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PublishResponse(%+v)", *p)
}

func (p *PublishResponse) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.PublishResponse",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*PublishResponse)(nil)

func (p *PublishResponse) Validate() error {
	return nil
}

// Attributes:
//   - Topics
type SubscribeRequest struct {
	Topics []string `thrift:"topics,1,required" db:"topics" json:"topics"`
}

func NewSubscribeRequest() *SubscribeRequest {
	return &SubscribeRequest{}
}

func (p *SubscribeRequest) GetTopics() []string {
	return p.Topics
}

func (p *SubscribeRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetTopics bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetTopics = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetTopics {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Topics is not set"))
	}
	return nil
}

func (p *SubscribeRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Topics = tSlice
	for i := 0; i < size; i++ {
		var _elem2 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem2 = v
		}
		p.Topics = append(p.Topics, _elem2)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *SubscribeRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "SubscribeRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *SubscribeRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "topics", thrift.LIST, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:topics: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRING, len(p.Topics)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Topics {
		if err := oprot.WriteString(ctx, string(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:topics: ", p), err)
	}
	return err
}

func (p *SubscribeRequest) Equals(other *SubscribeRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if len(p.Topics) != len(other.Topics) {
		return false
	}
	for i, _tgt := range p.Topics {
		_src3 := other.Topics[i]
		if _tgt != _src3 {
			return false
		}
	}
	return true
}

func (p *SubscribeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubscribeRequest(%+v)", *p)
}

func (p *SubscribeRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.SubscribeRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*SubscribeRequest)(nil)

func (p *SubscribeRequest) Validate() error {
	return nil
}

// Attributes:
//   - Topics
type UnsubscribeRequest struct {
	Topics []string `thrift:"topics,1,required" db:"topics" json:"topics"`
}

func NewUnsubscribeRequest() *UnsubscribeRequest {
	return &UnsubscribeRequest{}
}

func (p *UnsubscribeRequest) GetTopics() []string {
	return p.Topics
}

func (p *UnsubscribeRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetTopics bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetTopics = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetTopics {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Topics is not set"))
	}
	return nil
}

func (p *UnsubscribeRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]string, 0, size)
	p.Topics = tSlice
	for i := 0; i < size; i++ {
		var _elem4 string
		if v, err := iprot.ReadString(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_elem4 = v
		}
		p.Topics = append(p.Topics, _elem4)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *UnsubscribeRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "UnsubscribeRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *UnsubscribeRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "topics", thrift.LIST, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:topics: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.STRING, len(p.Topics)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Topics {
		if err := oprot.WriteString(ctx, string(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:topics: ", p), err)
	}
	return err
}

func (p *UnsubscribeRequest) Equals(other *UnsubscribeRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if len(p.Topics) != len(other.Topics) {
		return false
	}
	for i, _tgt := range p.Topics {
		_src5 := other.Topics[i]
		if _tgt != _src5 {
			return false
		}
	}
	return true
}

func (p *UnsubscribeRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnsubscribeRequest(%+v)", *p)
}

func (p *UnsubscribeRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.UnsubscribeRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*UnsubscribeRequest)(nil)

func (p *UnsubscribeRequest) Validate() error {
	return nil
}

// Attributes:
//   - SessionId
//   - ClientCapabilities
//   - UserAgent
//   - DeviceId
//   - FamilyDeviceId
//   - Subscription
//   - AppSpecificInfo
//   - Publishes
type ConnectRequest struct {
	SessionId          int64             `thrift:"sessionId,1,required" db:"sessionId" json:"sessionId"`
	ClientCapabilities int64             `thrift:"clientCapabilities,2,required" db:"clientCapabilities" json:"clientCapabilities"`
	UserAgent          string            `thrift:"userAgent,3,required" db:"userAgent" json:"userAgent"`
	DeviceId           string            `thrift:"deviceId,4,required" db:"deviceId" json:"deviceId"`
	FamilyDeviceId     string            `thrift:"familyDeviceId,5,required" db:"familyDeviceId" json:"familyDeviceId"`
	Subscription       *SubscribeRequest `thrift:"subscription,6,required" db:"subscription" json:"subscription"`
	AppSpecificInfo    *string           `thrift:"appSpecificInfo,7" db:"appSpecificInfo" json:"appSpecificInfo,omitempty"`
	Publishes          []*PublishRequest `thrift:"publishes,8" db:"publishes" json:"publishes,omitempty"`
}

func NewConnectRequest() *ConnectRequest {
	return &ConnectRequest{}
}

func (p *ConnectRequest) GetSessionId() int64 {
	return p.SessionId
}

func (p *ConnectRequest) GetClientCapabilities() int64 {
	return p.ClientCapabilities
}

func (p *ConnectRequest) GetUserAgent() string {
	return p.UserAgent
}

func (p *ConnectRequest) GetDeviceId() string {
	return p.DeviceId
}

func (p *ConnectRequest) GetFamilyDeviceId() string {
	return p.FamilyDeviceId
}

var ConnectRequest_Subscription_DEFAULT *SubscribeRequest

func (p *ConnectRequest) GetSubscription() *SubscribeRequest {
	if !p.IsSetSubscription() {
		return ConnectRequest_Subscription_DEFAULT
	}
	return p.Subscription
}

var ConnectRequest_AppSpecificInfo_DEFAULT string

func (p *ConnectRequest) GetAppSpecificInfo() string {
	if !p.IsSetAppSpecificInfo() {
		return ConnectRequest_AppSpecificInfo_DEFAULT
	}
	return *p.AppSpecificInfo
}

var ConnectRequest_Publishes_DEFAULT []*PublishRequest

func (p *ConnectRequest) GetPublishes() []*PublishRequest {
	return p.Publishes
}

func (p *ConnectRequest) IsSetSubscription() bool {
	return p.Subscription != nil
}

func (p *ConnectRequest) IsSetAppSpecificInfo() bool {
	return p.AppSpecificInfo != nil
}

func (p *ConnectRequest) IsSetPublishes() bool {
	return p.Publishes != nil
}

func (p *ConnectRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetSessionId bool = false
	var issetClientCapabilities bool = false
	var issetUserAgent bool = false
	var issetDeviceId bool = false
	var issetFamilyDeviceId bool = false
	var issetSubscription bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetSessionId = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetClientCapabilities = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
				issetUserAgent = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
				issetDeviceId = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
				issetFamilyDeviceId = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
				issetSubscription = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField8(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetSessionId {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field SessionId is not set"))
	}
	if !issetClientCapabilities {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ClientCapabilities is not set"))
	}
	if !issetUserAgent {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field UserAgent is not set"))
	}
	if !issetDeviceId {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field DeviceId is not set"))
	}
	if !issetFamilyDeviceId {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field FamilyDeviceId is not set"))
	}
	if !issetSubscription {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Subscription is not set"))
	}
	return nil
}

func (p *ConnectRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.SessionId = v
	}
	return nil
}

func (p *ConnectRequest) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.ClientCapabilities = v
	}
	return nil
}

func (p *ConnectRequest) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.UserAgent = v
	}
	return nil
}

func (p *ConnectRequest) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.DeviceId = v
	}
	return nil
}

func (p *ConnectRequest) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.FamilyDeviceId = v
	}
	return nil
}

func (p *ConnectRequest) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	p.Subscription = &SubscribeRequest{}
	if err := p.Subscription.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Subscription), err)
	}
	return nil
}

func (p *ConnectRequest) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		p.AppSpecificInfo = &v
	}
	return nil
}

func (p *ConnectRequest) ReadField8(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*PublishRequest, 0, size)
	p.Publishes = tSlice
	for i := 0; i < size; i++ {
		_elem6 := &PublishRequest{}
		if err := _elem6.Read(ctx, iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem6), err)
		}
		p.Publishes = append(p.Publishes, _elem6)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *ConnectRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ConnectRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField5(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField6(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField7(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField8(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ConnectRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "sessionId", thrift.I64, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:sessionId: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.SessionId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.sessionId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:sessionId: ", p), err)
	}
	return err
}

func (p *ConnectRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "clientCapabilities", thrift.I64, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:clientCapabilities: ", p), err)
	}
	if err := oprot.WriteI64(ctx, int64(p.ClientCapabilities)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.clientCapabilities (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:clientCapabilities: ", p), err)
	}
	return err
}

func (p *ConnectRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "userAgent", thrift.STRING, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:userAgent: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.UserAgent)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.userAgent (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:userAgent: ", p), err)
	}
	return err
}

func (p *ConnectRequest) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "deviceId", thrift.STRING, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:deviceId: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.DeviceId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.deviceId (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:deviceId: ", p), err)
	}
	return err
}

func (p *ConnectRequest) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "familyDeviceId", thrift.STRING, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:familyDeviceId: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.FamilyDeviceId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.familyDeviceId (5) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:familyDeviceId: ", p), err)
	}
	return err
}

func (p *ConnectRequest) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "subscription", thrift.STRUCT, 6); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:subscription: ", p), err)
	}
	if err := p.Subscription.Write(ctx, oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Subscription), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 6:subscription: ", p), err)
	}
	return err
}

func (p *ConnectRequest) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetAppSpecificInfo() {
		if err := oprot.WriteFieldBegin(ctx, "appSpecificInfo", thrift.STRING, 7); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:appSpecificInfo: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.AppSpecificInfo)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.appSpecificInfo (7) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 7:appSpecificInfo: ", p), err)
		}
	}
	return err
}

func (p *ConnectRequest) writeField8(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetPublishes() {
		if err := oprot.WriteFieldBegin(ctx, "publishes", thrift.LIST, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:publishes: ", p), err)
		}
		if err := oprot.WriteListBegin(ctx, thrift.STRUCT, len(p.Publishes)); err != nil {
			return thrift.PrependError("error writing list begin: ", err)
		}
		for _, v := range p.Publishes {
			if err := v.Write(ctx, oprot); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
			}
		}
		if err := oprot.WriteListEnd(ctx); err != nil {
			return thrift.PrependError("error writing list end: ", err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:publishes: ", p), err)
		}
	}
	return err
}

func (p *ConnectRequest) Equals(other *ConnectRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.SessionId != other.SessionId {
		return false
	}
	if p.ClientCapabilities != other.ClientCapabilities {
		return false
	}
	if p.UserAgent != other.UserAgent {
		return false
	}
	if p.DeviceId != other.DeviceId {
		return false
	}
	if p.FamilyDeviceId != other.FamilyDeviceId {
		return false
	}
	if !p.Subscription.Equals(other.Subscription) {
		return false
	}
	if p.AppSpecificInfo != other.AppSpecificInfo {
		if p.AppSpecificInfo == nil || other.AppSpecificInfo == nil {
			return false
		}
		if (*p.AppSpecificInfo) != (*other.AppSpecificInfo) {
			return false
		}
	}
	if len(p.Publishes) != len(other.Publishes) {
		return false
	}
	for i, _tgt := range p.Publishes {
		_src7 := other.Publishes[i]
		if !_tgt.Equals(_src7) {
			return false
		}
	}
	return true
}

func (p *ConnectRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConnectRequest(%+v)", *p)
}

func (p *ConnectRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.ConnectRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ConnectRequest)(nil)

func (p *ConnectRequest) Validate() error {
	return nil
}

// Attributes:
//   - InitialTitanSequenceID
//   - QueueType
//   - QueuePosition
//   - SyncAPIVersion
//   - MaxDeltasAbleToProcess
//   - DeltaBatchSize
//   - Encoding
//   - EntityFbid
//   - SyncDeviceID
//   - ClientFeatureID
type CreateIrisQueueRequest struct {
	InitialTitanSequenceID *int64  `thrift:"initial_titan_sequence_id,1" db:"initial_titan_sequence_id" json:"initial_titan_sequence_id,omitempty"`
	QueueType              *string `thrift:"queue_type,2" db:"queue_type" json:"queue_type,omitempty"`
	QueuePosition          *string `thrift:"queue_position,3" db:"queue_position" json:"queue_position,omitempty"`
	SyncAPIVersion         *int32  `thrift:"sync_api_version,4" db:"sync_api_version" json:"sync_api_version,omitempty"`
	MaxDeltasAbleToProcess *int32  `thrift:"max_deltas_able_to_process,5" db:"max_deltas_able_to_process" json:"max_deltas_able_to_process,omitempty"`
	DeltaBatchSize         *int32  `thrift:"delta_batch_size,6" db:"delta_batch_size" json:"delta_batch_size,omitempty"`
	Encoding               *string `thrift:"encoding,7" db:"encoding" json:"encoding,omitempty"`
	EntityFbid             *int64  `thrift:"entity_fbid,8" db:"entity_fbid" json:"entity_fbid,omitempty"`
	SyncDeviceID           *string `thrift:"sync_device_id,9" db:"sync_device_id" json:"sync_device_id,omitempty"`
	ClientFeatureID        *string `thrift:"client_feature_id,10" db:"client_feature_id" json:"client_feature_id,omitempty"`
}

func NewCreateIrisQueueRequest() *CreateIrisQueueRequest {
	return &CreateIrisQueueRequest{}
}

var CreateIrisQueueRequest_InitialTitanSequenceID_DEFAULT int64

func (p *CreateIrisQueueRequest) GetInitialTitanSequenceID() int64 {
	if !p.IsSetInitialTitanSequenceID() {
		return CreateIrisQueueRequest_InitialTitanSequenceID_DEFAULT
	}
	return *p.InitialTitanSequenceID
}

var CreateIrisQueueRequest_QueueType_DEFAULT string

func (p *CreateIrisQueueRequest) GetQueueType() string {
	if !p.IsSetQueueType() {
		return CreateIrisQueueRequest_QueueType_DEFAULT
	}
	return *p.QueueType
}

var CreateIrisQueueRequest_QueuePosition_DEFAULT string

func (p *CreateIrisQueueRequest) GetQueuePosition() string {
	if !p.IsSetQueuePosition() {
		return CreateIrisQueueRequest_QueuePosition_DEFAULT
	}
	return *p.QueuePosition
}

var CreateIrisQueueRequest_SyncAPIVersion_DEFAULT int32

func (p *CreateIrisQueueRequest) GetSyncAPIVersion() int32 {
	if !p.IsSetSyncAPIVersion() {
		return CreateIrisQueueRequest_SyncAPIVersion_DEFAULT
	}
	return *p.SyncAPIVersion
}

var CreateIrisQueueRequest_MaxDeltasAbleToProcess_DEFAULT int32

func (p *CreateIrisQueueRequest) GetMaxDeltasAbleToProcess() int32 {
	if !p.IsSetMaxDeltasAbleToProcess() {
		return CreateIrisQueueRequest_MaxDeltasAbleToProcess_DEFAULT
	}
	return *p.MaxDeltasAbleToProcess
}

var CreateIrisQueueRequest_DeltaBatchSize_DEFAULT int32

func (p *CreateIrisQueueRequest) GetDeltaBatchSize() int32 {
	if !p.IsSetDeltaBatchSize() {
		return CreateIrisQueueRequest_DeltaBatchSize_DEFAULT
	}
	return *p.DeltaBatchSize
}

var CreateIrisQueueRequest_Encoding_DEFAULT string

func (p *CreateIrisQueueRequest) GetEncoding() string {
	if !p.IsSetEncoding() {
		return CreateIrisQueueRequest_Encoding_DEFAULT
	}
	return *p.Encoding
}

var CreateIrisQueueRequest_EntityFbid_DEFAULT int64

func (p *CreateIrisQueueRequest) GetEntityFbid() int64 {
	if !p.IsSetEntityFbid() {
		return CreateIrisQueueRequest_EntityFbid_DEFAULT
	}
	return *p.EntityFbid
}

var CreateIrisQueueRequest_SyncDeviceID_DEFAULT string

func (p *CreateIrisQueueRequest) GetSyncDeviceID() string {
	if !p.IsSetSyncDeviceID() {
		return CreateIrisQueueRequest_SyncDeviceID_DEFAULT
	}
	return *p.SyncDeviceID
}

var CreateIrisQueueRequest_ClientFeatureID_DEFAULT string

func (p *CreateIrisQueueRequest) GetClientFeatureID() string {
	if !p.IsSetClientFeatureID() {
		return CreateIrisQueueRequest_ClientFeatureID_DEFAULT
	}
	return *p.ClientFeatureID
}

func (p *CreateIrisQueueRequest) IsSetInitialTitanSequenceID() bool {
	return p.InitialTitanSequenceID != nil
}

func (p *CreateIrisQueueRequest) IsSetQueueType() bool {
	return p.QueueType != nil
}

func (p *CreateIrisQueueRequest) IsSetQueuePosition() bool {
	return p.QueuePosition != nil
}

func (p *CreateIrisQueueRequest) IsSetSyncAPIVersion() bool {
	return p.SyncAPIVersion != nil
}

func (p *CreateIrisQueueRequest) IsSetMaxDeltasAbleToProcess() bool {
	return p.MaxDeltasAbleToProcess != nil
}

func (p *CreateIrisQueueRequest) IsSetDeltaBatchSize() bool {
	return p.DeltaBatchSize != nil
}

func (p *CreateIrisQueueRequest) IsSetEncoding() bool {
	return p.Encoding != nil
}

func (p *CreateIrisQueueRequest) IsSetEntityFbid() bool {
	return p.EntityFbid != nil
}

func (p *CreateIrisQueueRequest) IsSetSyncDeviceID() bool {
	return p.SyncDeviceID != nil
}

func (p *CreateIrisQueueRequest) IsSetClientFeatureID() bool {
	return p.ClientFeatureID != nil
}

func (p *CreateIrisQueueRequest) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField8(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 9:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField9(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 10:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField10(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.InitialTitanSequenceID = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.QueueType = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.QueuePosition = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.SyncAPIVersion = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.MaxDeltasAbleToProcess = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 6: ", err)
	} else {
		p.DeltaBatchSize = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		p.Encoding = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField8(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(ctx); err != nil {
		return thrift.PrependError("error reading field 8: ", err)
	} else {
		p.EntityFbid = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField9(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 9: ", err)
	} else {
		p.SyncDeviceID = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) ReadField10(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 10: ", err)
	} else {
		p.ClientFeatureID = &v
	}
	return nil
}

func (p *CreateIrisQueueRequest) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "CreateIrisQueueRequest"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField5(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField6(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField7(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField8(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField9(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField10(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CreateIrisQueueRequest) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetInitialTitanSequenceID() {
		if err := oprot.WriteFieldBegin(ctx, "initial_titan_sequence_id", thrift.I64, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:initial_titan_sequence_id: ", p), err)
		}
		if err := oprot.WriteI64(ctx, int64(*p.InitialTitanSequenceID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.initial_titan_sequence_id (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:initial_titan_sequence_id: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetQueueType() {
		if err := oprot.WriteFieldBegin(ctx, "queue_type", thrift.STRING, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:queue_type: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.QueueType)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.queue_type (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:queue_type: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetQueuePosition() {
		if err := oprot.WriteFieldBegin(ctx, "queue_position", thrift.STRING, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:queue_position: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.QueuePosition)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.queue_position (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:queue_position: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSyncAPIVersion() {
		if err := oprot.WriteFieldBegin(ctx, "sync_api_version", thrift.I32, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:sync_api_version: ", p), err)
		}
		if err := oprot.WriteI32(ctx, int32(*p.SyncAPIVersion)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.sync_api_version (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:sync_api_version: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetMaxDeltasAbleToProcess() {
		if err := oprot.WriteFieldBegin(ctx, "max_deltas_able_to_process", thrift.I32, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:max_deltas_able_to_process: ", p), err)
		}
		if err := oprot.WriteI32(ctx, int32(*p.MaxDeltasAbleToProcess)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.max_deltas_able_to_process (5) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:max_deltas_able_to_process: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetDeltaBatchSize() {
		if err := oprot.WriteFieldBegin(ctx, "delta_batch_size", thrift.I32, 6); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:delta_batch_size: ", p), err)
		}
		if err := oprot.WriteI32(ctx, int32(*p.DeltaBatchSize)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.delta_batch_size (6) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 6:delta_batch_size: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetEncoding() {
		if err := oprot.WriteFieldBegin(ctx, "encoding", thrift.STRING, 7); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:encoding: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.Encoding)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.encoding (7) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 7:encoding: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField8(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetEntityFbid() {
		if err := oprot.WriteFieldBegin(ctx, "entity_fbid", thrift.I64, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:entity_fbid: ", p), err)
		}
		if err := oprot.WriteI64(ctx, int64(*p.EntityFbid)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.entity_fbid (8) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:entity_fbid: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField9(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSyncDeviceID() {
		if err := oprot.WriteFieldBegin(ctx, "sync_device_id", thrift.STRING, 9); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:sync_device_id: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.SyncDeviceID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.sync_device_id (9) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 9:sync_device_id: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) writeField10(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetClientFeatureID() {
		if err := oprot.WriteFieldBegin(ctx, "client_feature_id", thrift.STRING, 10); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:client_feature_id: ", p), err)
		}
		if err := oprot.WriteString(ctx, string(*p.ClientFeatureID)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.client_feature_id (10) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 10:client_feature_id: ", p), err)
		}
	}
	return err
}

func (p *CreateIrisQueueRequest) Equals(other *CreateIrisQueueRequest) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.InitialTitanSequenceID != other.InitialTitanSequenceID {
		if p.InitialTitanSequenceID == nil || other.InitialTitanSequenceID == nil {
			return false
		}
		if (*p.InitialTitanSequenceID) != (*other.InitialTitanSequenceID) {
			return false
		}
	}
	if p.QueueType != other.QueueType {
		if p.QueueType == nil || other.QueueType == nil {
			return false
		}
		if (*p.QueueType) != (*other.QueueType) {
			return false
		}
	}
	if p.QueuePosition != other.QueuePosition {
		if p.QueuePosition == nil || other.QueuePosition == nil {
			return false
		}
		if (*p.QueuePosition) != (*other.QueuePosition) {
			return false
		}
	}
	if p.SyncAPIVersion != other.SyncAPIVersion {
		if p.SyncAPIVersion == nil || other.SyncAPIVersion == nil {
			return false
		}
		if (*p.SyncAPIVersion) != (*other.SyncAPIVersion) {
			return false
		}
	}
	if p.MaxDeltasAbleToProcess != other.MaxDeltasAbleToProcess {
		if p.MaxDeltasAbleToProcess == nil || other.MaxDeltasAbleToProcess == nil {
			return false
		}
		if (*p.MaxDeltasAbleToProcess) != (*other.MaxDeltasAbleToProcess) {
			return false
		}
	}
	if p.DeltaBatchSize != other.DeltaBatchSize {
		if p.DeltaBatchSize == nil || other.DeltaBatchSize == nil {
			return false
		}
		if (*p.DeltaBatchSize) != (*other.DeltaBatchSize) {
			return false
		}
	}
	if p.Encoding != other.Encoding {
		if p.Encoding == nil || other.Encoding == nil {
			return false
		}
		if (*p.Encoding) != (*other.Encoding) {
			return false
		}
	}
	if p.EntityFbid != other.EntityFbid {
		if p.EntityFbid == nil || other.EntityFbid == nil {
			return false
		}
		if (*p.EntityFbid) != (*other.EntityFbid) {
			return false
		}
	}
	if p.SyncDeviceID != other.SyncDeviceID {
		if p.SyncDeviceID == nil || other.SyncDeviceID == nil {
			return false
		}
		if (*p.SyncDeviceID) != (*other.SyncDeviceID) {
			return false
		}
	}
	if p.ClientFeatureID != other.ClientFeatureID {
		if p.ClientFeatureID == nil || other.ClientFeatureID == nil {
			return false
		}
		if (*p.ClientFeatureID) != (*other.ClientFeatureID) {
			return false
		}
	}
	return true
}

func (p *CreateIrisQueueRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateIrisQueueRequest(%+v)", *p)
}

func (p *CreateIrisQueueRequest) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.CreateIrisQueueRequest",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*CreateIrisQueueRequest)(nil)

func (p *CreateIrisQueueRequest) Validate() error {
	return nil
}

// Attributes:
//   - Code
//   - Message
type ErrorResponse struct {
	Code    ErrorCode `thrift:"code,1,required" db:"code" json:"code"`
	Message string    `thrift:"message,2,required" db:"message" json:"message"`
}

func NewErrorResponse() *ErrorResponse {
	return &ErrorResponse{}
}

func (p *ErrorResponse) GetCode() ErrorCode {
	return p.Code
}

func (p *ErrorResponse) GetMessage() string {
	return p.Message
}

func (p *ErrorResponse) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetCode bool = false
	var issetMessage bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
				issetCode = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
				issetMessage = true
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetCode {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Code is not set"))
	}
	if !issetMessage {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Message is not set"))
	}
	return nil
}

func (p *ErrorResponse) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		temp := ErrorCode(v)
		p.Code = temp
	}
	return nil
}

func (p *ErrorResponse) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Message = v
	}
	return nil
}

func (p *ErrorResponse) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "ErrorResponse"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ErrorResponse) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "code", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:code: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Code)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.code (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:code: ", p), err)
	}
	return err
}

func (p *ErrorResponse) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "message", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:message: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Message)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.message (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:message: ", p), err)
	}
	return err
}

func (p *ErrorResponse) Equals(other *ErrorResponse) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Code != other.Code {
		return false
	}
	if p.Message != other.Message {
		return false
	}
	return true
}

func (p *ErrorResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ErrorResponse(%+v)", *p)
}

func (p *ErrorResponse) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.ErrorResponse",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ErrorResponse)(nil)

func (p *ErrorResponse) Validate() error {
	return nil
}

// Attributes:
//   - ConnectRequest
//   - PublishRequest
//   - SubscribeRequest
//   - UnsubscribeRequest
type RequestPayload struct {
	ConnectRequest     *ConnectRequest     `thrift:"connectRequest,1" db:"connectRequest" json:"connectRequest,omitempty"`
	PublishRequest     *PublishRequest     `thrift:"publishRequest,2" db:"publishRequest" json:"publishRequest,omitempty"`
	SubscribeRequest   *SubscribeRequest   `thrift:"subscribeRequest,3" db:"subscribeRequest" json:"subscribeRequest,omitempty"`
	UnsubscribeRequest *UnsubscribeRequest `thrift:"unsubscribeRequest,4" db:"unsubscribeRequest" json:"unsubscribeRequest,omitempty"`
}

func NewRequestPayload() *RequestPayload {
	return &RequestPayload{}
}

var RequestPayload_ConnectRequest_DEFAULT *ConnectRequest

func (p *RequestPayload) GetConnectRequest() *ConnectRequest {
	if !p.IsSetConnectRequest() {
		return RequestPayload_ConnectRequest_DEFAULT
	}
	return p.ConnectRequest
}

var RequestPayload_PublishRequest_DEFAULT *PublishRequest

func (p *RequestPayload) GetPublishRequest() *PublishRequest {
	if !p.IsSetPublishRequest() {
		return RequestPayload_PublishRequest_DEFAULT
	}
	return p.PublishRequest
}

var RequestPayload_SubscribeRequest_DEFAULT *SubscribeRequest

func (p *RequestPayload) GetSubscribeRequest() *SubscribeRequest {
	if !p.IsSetSubscribeRequest() {
		return RequestPayload_SubscribeRequest_DEFAULT
	}
	return p.SubscribeRequest
}

var RequestPayload_UnsubscribeRequest_DEFAULT *UnsubscribeRequest

func (p *RequestPayload) GetUnsubscribeRequest() *UnsubscribeRequest {
	if !p.IsSetUnsubscribeRequest() {
		return RequestPayload_UnsubscribeRequest_DEFAULT
	}
	return p.UnsubscribeRequest
}

func (p *RequestPayload) CountSetFieldsRequestPayload() int {
	count := 0
	if p.IsSetConnectRequest() {
		count++
	}
	if p.IsSetPublishRequest() {
		count++
	}
	if p.IsSetSubscribeRequest() {
		count++
	}
	if p.IsSetUnsubscribeRequest() {
		count++
	}
	return count

}

func (p *RequestPayload) IsSetConnectRequest() bool {
	return p.ConnectRequest != nil
}

func (p *RequestPayload) IsSetPublishRequest() bool {
	return p.PublishRequest != nil
}

func (p *RequestPayload) IsSetSubscribeRequest() bool {
	return p.SubscribeRequest != nil
}

func (p *RequestPayload) IsSetUnsubscribeRequest() bool {
	return p.UnsubscribeRequest != nil
}

func (p *RequestPayload) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *RequestPayload) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.ConnectRequest = &ConnectRequest{}
	if err := p.ConnectRequest.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ConnectRequest), err)
	}
	return nil
}

func (p *RequestPayload) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	p.PublishRequest = &PublishRequest{}
	if err := p.PublishRequest.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.PublishRequest), err)
	}
	return nil
}

func (p *RequestPayload) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	p.SubscribeRequest = &SubscribeRequest{}
	if err := p.SubscribeRequest.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.SubscribeRequest), err)
	}
	return nil
}

func (p *RequestPayload) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	p.UnsubscribeRequest = &UnsubscribeRequest{}
	if err := p.UnsubscribeRequest.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.UnsubscribeRequest), err)
	}
	return nil
}

func (p *RequestPayload) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if c := p.CountSetFieldsRequestPayload(); c != 1 {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("%T write union: exactly one field must be set (%d set)", p, c))
	}
	if err := oprot.WriteStructBegin(ctx, "RequestPayload"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField3(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField4(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *RequestPayload) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetConnectRequest() {
		if err := oprot.WriteFieldBegin(ctx, "connectRequest", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:connectRequest: ", p), err)
		}
		if err := p.ConnectRequest.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ConnectRequest), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:connectRequest: ", p), err)
		}
	}
	return err
}

func (p *RequestPayload) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetPublishRequest() {
		if err := oprot.WriteFieldBegin(ctx, "publishRequest", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:publishRequest: ", p), err)
		}
		if err := p.PublishRequest.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.PublishRequest), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:publishRequest: ", p), err)
		}
	}
	return err
}

func (p *RequestPayload) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSubscribeRequest() {
		if err := oprot.WriteFieldBegin(ctx, "subscribeRequest", thrift.STRUCT, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:subscribeRequest: ", p), err)
		}
		if err := p.SubscribeRequest.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.SubscribeRequest), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:subscribeRequest: ", p), err)
		}
	}
	return err
}

func (p *RequestPayload) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetUnsubscribeRequest() {
		if err := oprot.WriteFieldBegin(ctx, "unsubscribeRequest", thrift.STRUCT, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:unsubscribeRequest: ", p), err)
		}
		if err := p.UnsubscribeRequest.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.UnsubscribeRequest), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:unsubscribeRequest: ", p), err)
		}
	}
	return err
}

func (p *RequestPayload) Equals(other *RequestPayload) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.ConnectRequest.Equals(other.ConnectRequest) {
		return false
	}
	if !p.PublishRequest.Equals(other.PublishRequest) {
		return false
	}
	if !p.SubscribeRequest.Equals(other.SubscribeRequest) {
		return false
	}
	if !p.UnsubscribeRequest.Equals(other.UnsubscribeRequest) {
		return false
	}
	return true
}

func (p *RequestPayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RequestPayload(%+v)", *p)
}

func (p *RequestPayload) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.RequestPayload",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*RequestPayload)(nil)

func (p *RequestPayload) Validate() error {
	return nil
}

// Attributes:
//   - PublishResponse
//   - ErrorResponse
type ResponsePayload struct {
	PublishResponse *PublishResponse `thrift:"publishResponse,1" db:"publishResponse" json:"publishResponse,omitempty"`
	ErrorResponse   *ErrorResponse   `thrift:"errorResponse,2" db:"errorResponse" json:"errorResponse,omitempty"`
}

func NewResponsePayload() *ResponsePayload {
	return &ResponsePayload{}
}

var ResponsePayload_PublishResponse_DEFAULT *PublishResponse

func (p *ResponsePayload) GetPublishResponse() *PublishResponse {
	if !p.IsSetPublishResponse() {
		return ResponsePayload_PublishResponse_DEFAULT
	}
	return p.PublishResponse
}

var ResponsePayload_ErrorResponse_DEFAULT *ErrorResponse

func (p *ResponsePayload) GetErrorResponse() *ErrorResponse {
	if !p.IsSetErrorResponse() {
		return ResponsePayload_ErrorResponse_DEFAULT
	}
	return p.ErrorResponse
}

func (p *ResponsePayload) CountSetFieldsResponsePayload() int {
	count := 0
	if p.IsSetPublishResponse() {
		count++
	}
	if p.IsSetErrorResponse() {
		count++
	}
	return count

}

func (p *ResponsePayload) IsSetPublishResponse() bool {
	return p.PublishResponse != nil
}

func (p *ResponsePayload) IsSetErrorResponse() bool {
	return p.ErrorResponse != nil
}

func (p *ResponsePayload) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ResponsePayload) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	p.PublishResponse = &PublishResponse{}
	if err := p.PublishResponse.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.PublishResponse), err)
	}
	return nil
}

func (p *ResponsePayload) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	p.ErrorResponse = &ErrorResponse{}
	if err := p.ErrorResponse.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ErrorResponse), err)
	}
	return nil
}

func (p *ResponsePayload) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if c := p.CountSetFieldsResponsePayload(); c != 1 {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("%T write union: exactly one field must be set (%d set)", p, c))
	}
	if err := oprot.WriteStructBegin(ctx, "ResponsePayload"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil {
			return err
		}
		if err := p.writeField2(ctx, oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ResponsePayload) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetPublishResponse() {
		if err := oprot.WriteFieldBegin(ctx, "publishResponse", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:publishResponse: ", p), err)
		}
		if err := p.PublishResponse.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.PublishResponse), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:publishResponse: ", p), err)
		}
	}
	return err
}

func (p *ResponsePayload) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetErrorResponse() {
		if err := oprot.WriteFieldBegin(ctx, "errorResponse", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:errorResponse: ", p), err)
		}
		if err := p.ErrorResponse.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ErrorResponse), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:errorResponse: ", p), err)
		}
	}
	return err
}

func (p *ResponsePayload) Equals(other *ResponsePayload) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if !p.PublishResponse.Equals(other.PublishResponse) {
		return false
	}
	if !p.ErrorResponse.Equals(other.ErrorResponse) {
		return false
	}
	return true
}

func (p *ResponsePayload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ResponsePayload(%+v)", *p)
}

func (p *ResponsePayload) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type:  "*mqttbypass.ResponsePayload",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*ResponsePayload)(nil)

func (p *ResponsePayload) Validate() error {
	return nil
}

//lint:file-ignore ST1005 The thrift generator is bad
